Repository prgrms-web-devcourse/Team-Meoguri-Linkocean-BE, pull requests merged in 2022-07, with the labels that each got.

#1 [LO-3] PR Template 추가
  .github/pull_request_template.md
  .gitignore
Labels: docs

#2 [LO-3] PR Template 추가
  .github/pull_request_template.md
  .gitignore
Labels: docs

#4 [LO-6] 사용자 도메인 모델 개발
  build.gradle
  src/main/java/com/meoguri/linkocean/domain/common/BaseIdEntity.java
  src/main/java/com/meoguri/linkocean/domain/user/entity/Email.java
  src/main/java/com/meoguri/linkocean/domain/user/entity/OAuthType.java
  src/main/java/com/meoguri/linkocean/domain/user/entity/User.java
  src/test/java/com/meoguri/linkocean/domain/user/entity/EmailTest.java
  src/test/java/com/meoguri/linkocean/domain/user/entity/UserTest.java
  src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
Labels: 로그인

#5 [LO-11] 코딩 컨벤션 설정
  build.gradle
  config/checkstyle/naver-checkstyle-rules.xml
  config/checkstyle/naver-intellij-formatter.xml
  src/main/java/com/meoguri/linkocean/LinkoceanApplication.java
  src/main/java/com/meoguri/linkocean/domain/common/BaseIdEntity.java
  src/main/java/com/meoguri/linkocean/domain/user/entity/Email.java
  src/main/java/com/meoguri/linkocean/domain/user/entity/OAuthType.java
  src/main/java/com/meoguri/linkocean/domain/user/entity/User.java
  src/test/java/com/meoguri/linkocean/LinkoceanApplicationTests.java
  src/test/java/com/meoguri/linkocean/domain/user/entity/EmailTest.java
  src/test/java/com/meoguri/linkocean/domain/user/entity/UserTest.java
  src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
Labels: 세팅

#6 [LO-10] 회원 기능 도메인
  build.gradle
  src/main/java/com/meoguri/linkocean/LinkoceanApplication.java
  src/main/java/com/meoguri/linkocean/domain/user/entity/Email.java
  src/main/java/com/meoguri/linkocean/domain/user/entity/User.java
  src/test/java/com/meoguri/linkocean/domain/user/entity/EmailTest.java
  src/test/java/com/meoguri/linkocean/domain/user/entity/UserTest.java
Labels: 로그인

#7 [LO-12] 프로필 기능 도메인
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
  src/test/java/com/meoguri/linkocean/domain/profile/entity/ProfileTest.java
  src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
Labels: 프로필

#8 [LO-13] 북마크 도메인 개발
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/OpenType.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Url.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
  src/main/java/com/meoguri/linkocean/domain/user/entity/User.java
  src/main/resources/application.yml
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/UrlTest.java
  src/test/java/com/meoguri/linkocean/domain/user/entity/UserTest.java
  src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
Labels: 북마크

#9 [LO-14] 예외처리 로직 빼기
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Url.java
  src/main/java/com/meoguri/linkocean/domain/common/Preconditions.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
Labels: 세팅

#11 [LO-17] 카테고리 도메인 엔티티 개발
  src/main/java/com/meoguri/linkocean/domain/category/entity/Category.java
  src/main/java/com/meoguri/linkocean/domain/category/entity/FavoriteCategory.java
Labels: 카테고리

#14 [ LO-19] Preconditions 리팩토링
  src/main/java/com/meoguri/linkocean/exception/Preconditions.java
Labels: 세팅

#15 [LO-20] 링크 메타데이터 도메인 엔티티 개발
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/LinkMetadata.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/LinkMetadataTest.java
  src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
Labels: 북마크

#16 [LO-22] PR 전용 GitHub Actions 추가
  .github/workflows/test-every-pull-request.yml
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/LinkMetadataTest.java
Labels: 세팅

#17 [LO-24] Jacoco 라이브러리 도입
  build.gradle
Labels: 세팅

#19 [LO-23] application yml 설정 + h2 데이터베이스 환경 삭제
  build.gradle
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 세팅

#20 [HotFix] Test DB는 H2 DB 바라보도록 수정
  build.gradle
  src/test/resources/application.yml
Labels: 세팅

#25 [LO-28] 카테고리, 선호 카테고리 저장 기능
  src/main/java/com/meoguri/linkocean/domain/category/entity/Category.java
  src/main/java/com/meoguri/linkocean/domain/category/repository/CategoryRepository.java
  src/main/java/com/meoguri/linkocean/domain/category/repository/FavoriteCategoryRepository.java
  src/main/java/com/meoguri/linkocean/domain/category/service/CategoryService.java
  src/main/java/com/meoguri/linkocean/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/category/service/FavoriteCategoryService.java
  src/main/java/com/meoguri/linkocean/domain/category/service/FavoriteCategoryServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/category/service/dto/AddFavoriteCategoriesCommand.java
  src/main/java/com/meoguri/linkocean/exception/LinkoceanRuntimeException.java
  src/main/resources/db/sql/InsertCategories.sql
  src/test/java/com/meoguri/linkocean/domain/category/repository/CategoryRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/category/service/CategoryServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/category/service/FavoriteCategoryServiceImplTest.java
Labels: 카테고리

#29 [LO-30] 링크 메타데이터 동기화 기능 개발
  src/main/java/com/meoguri/linkocean/LinkoceanApplication.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/repository/LinkMetadataRepository.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/LinkMetadata.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/vo/Url.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/repository/LinkMetadataRepository.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/scheduler/LinkMetadataSynchronizeScheduler.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataService.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/dto/PutLinkMetadataResult.java
  src/test/java/com/meoguri/linkocean/common/DependencyRuleTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/LinkMetadataTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/entity/LinkMetadataTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/entity/vo/UrlTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/repository/LinkMetadataRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/scheduler/LinkMetadataSynchronizeSchedulerTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
Labels: 링크

#27 [LO-33] 북마크 리액션 추가/취소 서비스 계층
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Reaction.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/repository/ReactionRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/GetBookmarkByIdQuery.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/ReactionCommand.java
  src/main/java/com/meoguri/linkocean/domain/profile/repository/ProfileRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/GetProfileByUserIdQuery.java
  src/main/java/com/meoguri/linkocean/domain/user/repository/UserRepository.java
  src/main/java/com/meoguri/linkocean/exception/LinkoceanRuntimeException.java
  src/main/java/com/meoguri/linkocean/exception/Preconditions.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/ReactionTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/repository/ReactionRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/GetBookmarkByIdQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/repository/ProfileRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/GetProfileByUserIdQueryTest.java
Labels: 리액션

#33 [LO-36] 링크 메타데이터 동기화 기능 리펙토링
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/scheduler/LinkMetadataSynchronizeScheduler.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataService.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
Labels: 링크

#31 [LO-31] 구글 OAuth2 클라이언트 연동
  .github/workflows/test-every-pull-request.yml
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/com/meoguri/linkocean/configuration/security/SecurityConfiguration.java
  src/main/java/com/meoguri/linkocean/configuration/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/meoguri/linkocean/configuration/security/oauth/OAuthAttributes.java
  src/main/java/com/meoguri/linkocean/configuration/security/oauth/SessionUser.java
  src/main/java/com/meoguri/linkocean/domain/user/entity/vo/Email.java
  src/main/java/com/meoguri/linkocean/domain/user/repository/UserRepository.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V014__ADD_AUTO_INCREMENT.sql
  src/main/resources/templates/index.html
  src/test/java/com/meoguri/linkocean/common/DependencyRuleTest.java
  src/test/java/com/meoguri/linkocean/configuration/security/oauth/OAuthAttributesTest.java
  src/test/java/com/meoguri/linkocean/configuration/security/oauth/SessionUserTest.java
  src/test/java/com/meoguri/linkocean/domain/category/service/CategoryServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/category/service/FavoriteCategoryServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/scheduler/LinkMetadataSynchronizeSchedulerTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
  src/test/resources/application.yml
Labels: 로그인

#32 [LO-38] 영속성 패키지 이름 변경, Query 영속성 패키지로 이동
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/GetBookmarkByIdQuery.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/category/persistence/CategoryRepository.java
  src/main/java/com/meoguri/linkocean/domain/category/persistence/FavoriteCategoryRepository.java
  src/main/java/com/meoguri/linkocean/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/category/service/FavoriteCategoryServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/persistence/LinkMetadataRepository.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/GetProfileByUserIdQuery.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/ProfileRepository.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/GetBookmarkByIdQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/category/persistence/CategoryRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/category/service/CategoryServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/category/service/FavoriteCategoryServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/LinkMetadataRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/GetProfileByUserIdQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/ProfileRepositoryTest.java
Labels: 세팅

#37 [LO-38] Dependency RuleTest 살리기, Query 추가
  src/main/java/com/meoguri/linkocean/annotation/Query.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/GetBookmarkByIdQuery.java
  src/main/java/com/meoguri/linkocean/domain/category/persistence/FindCategoriesByNamesQuery.java
  src/main/java/com/meoguri/linkocean/domain/category/service/CategoryService.java
  src/main/java/com/meoguri/linkocean/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/category/service/FavoriteCategoryServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/GetProfileByUserIdQuery.java
  src/test/java/com/meoguri/linkocean/common/DependencyRuleTest.java
  src/test/java/com/meoguri/linkocean/domain/category/persistence/FindCategoriesByNamesQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/category/service/FavoriteCategoryServiceTest.java
Labels: 세팅

#41 [LO-42] 카테고리 이넘으로 변경
  src/main/java/com/meoguri/linkocean/domain/category/entity/Category.java
  src/main/java/com/meoguri/linkocean/domain/category/entity/FavoriteCategory.java
  src/main/java/com/meoguri/linkocean/domain/category/persistence/CategoryRepository.java
  src/main/java/com/meoguri/linkocean/domain/category/persistence/FavoriteCategoryRepository.java
  src/main/java/com/meoguri/linkocean/domain/category/persistence/FindCategoriesByNamesQuery.java
  src/main/java/com/meoguri/linkocean/domain/category/service/FavoriteCategoryService.java
  src/main/java/com/meoguri/linkocean/domain/category/service/FavoriteCategoryServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/category/service/dto/AddFavoriteCategoriesCommand.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategory.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/dto/RegisterProfileCommand.java
  src/main/resources/db/sql/InsertCategories.sql
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/category/persistence/CategoryRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/category/persistence/FindCategoriesByNamesQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/category/service/FavoriteCategoryServiceTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/LinkMetadataRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImplTest.java
Labels: 카테고리

#42 [LO-43] 팔로우/언팔로우 서비스
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/FindProfileByIdQuery.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/FindProfileByUserIdQuery.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/FollowService.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/FollowServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/dto/FollowCommand.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/FindProfileByIdQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/FindProfileByUserIdQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/FollowServiceImplTest.java
Labels: 팔로우

#46 [LO-48] enum 동작 방식 통일
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Reaction.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/vo/OpenType.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/ReactionCommand.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategory.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/ReactionTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
Labels: 세팅

#47 [LO-47] 팔로우 숫자 조회 리포리토리 구현 후 프로필 조회 서비스에 반영
  src/main/java/com/meoguri/linkocean/annotation/Query.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileService.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/dto/UpdateProfileCommand.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/FollowServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImplTest.java
Labels: 팔로우

#50 [LO-68] 팔로워/팔로이 목록조회 초벌
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/ProfileRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/dto/FindProfileCond.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileService.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/dto/GetMyProfileResult.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/dto/ProfileSearchCond.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/dto/SearchProfileResult.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImplTest.java
Labels: 팔로우, 프로필

#52 [LO-63] 카테고리 전체 목록 조회 API
  checkstyle/naver-checkstyle-rules.xml
  src/main/java/com/meoguri/linkocean/controller/CategoryController.java
  src/main/java/com/meoguri/linkocean/controller/dto/category/AllCategoriesResponse.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/CategoryService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImpl.java
  src/test/java/com/meoguri/linkocean/common/DependencyRuleTest.java
  src/test/java/com/meoguri/linkocean/controller/BaseControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/CategoryControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImplTest.java
Labels: 카테고리

#53 [LO-49] QueryDSL 설정
  build.gradle
  src/main/java/com/meoguri/linkocean/configuration/querydsl/QueryDslConfig.java
  src/test/java/com/meoguri/linkocean/configuration/querydsl/QueryDslConfigTest.java
Labels: 세팅

#54 [LO-70] CustomControllerAdvice 초벌 추가
  src/main/java/com/meoguri/linkocean/controller/CustomControllerAdvice.java
Labels: 세팅

#55 [LO-71] .gitignore에 설정 파일 추가하기
  .gitignore
Labels: 세팅

#56 [LO-72] contextLoad 테스트는 local 프로파일에서 수행하도록 수정
  .github/workflows/test-every-pull-request.yml
  src/test/java/com/meoguri/linkocean/LinkoceanApplicationTests.java
Labels: 세팅

#58 [LO-74] 에러 페이지 추가
  src/main/java/com/meoguri/linkocean/configuration/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/meoguri/linkocean/controller/CustomRestControllerAdvice.java
  src/main/java/com/meoguri/linkocean/controller/category/CategoryController.java
  src/main/java/com/meoguri/linkocean/controller/category/dto/AllCategoriesResponse.java
  src/main/resources/templates/error.html
  src/test/java/com/meoguri/linkocean/controller/BaseControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/category/CategoryControllerTest.java
Labels: 세팅

#59 [LO-76] 팔로워/팔로이 목록 조회 서비스 마무리
  checkstyle/naver-checkstyle-rules.xml
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
  src/test/java/com/meoguri/linkocean/controller/category/CategoryControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImplTest.java
Labels: 프로필

#68 [LO-64] 태그 목록 조회 Api
  src/main/java/com/meoguri/linkocean/configuration/security/SecurityConfiguration.java
  src/main/java/com/meoguri/linkocean/configuration/security/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/meoguri/linkocean/configuration/security/oauth/SecurityOAuthType.java
  src/main/java/com/meoguri/linkocean/controller/ListResponse.java
  src/main/java/com/meoguri/linkocean/controller/ListResponseJsonSerializer.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/TagController.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/MyTagsResponse.java
  src/main/java/com/meoguri/linkocean/controller/category/CategoryController.java
  src/main/java/com/meoguri/linkocean/controller/category/dto/AllCategoriesResponse.java
  src/main/java/com/meoguri/linkocean/controller/user/LoginController.java
  src/main/java/com/meoguri/linkocean/controller/user/dto/LoginSuccessResponse.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/TagService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/TagServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetMyTagsResult.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/TagControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/user/LoginControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/TagServiceImplTest.java
Labels: 태그

#70 [LO-82] 북마크 수정 서비스 개발
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/UpdateBookmarkCommand.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
Labels: 북마크

#69 [LO-84] 즐겨찾기 추가/제거 서비스
  build.gradle
  lombok.config
  src/main/java/com/meoguri/linkocean/annotation/Query.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/FindBookmarkByIdQuery.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/LinkMetadata.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/vo/Url.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
  src/main/java/com/meoguri/linkocean/exception/LinkoceanRuntimeException.java
  src/main/java/com/meoguri/linkocean/exception/Preconditions.java
  src/main/java/com/meoguri/linkocean/infrastructure/jsoup/SearchLinkMetadataResult.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/entity/vo/UrlTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByUrlQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImplTest.java
Labels: 북마크

#72 [LO-53] security 설정 및 이슈 해결, 앞으로 ControllerTest에선 @WithMockUser를!
  build.gradle
  src/main/java/com/meoguri/linkocean/configuration/security/SecurityConfiguration.java
  src/main/java/com/meoguri/linkocean/configuration/security/oauth/CustomAuthenticationEntryPoint.java
  src/main/java/com/meoguri/linkocean/configuration/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/meoguri/linkocean/configuration/security/oauth/SessionUser.java
  src/main/java/com/meoguri/linkocean/controller/CustomRestControllerAdvice.java
  src/test/java/com/meoguri/linkocean/controller/category/CategoryControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/user/LoginControllerTest.java
Labels: 로그인

#73 [LO-87] Session 저장소 Embedded -> DB로 변경
  build.gradle
  src/main/java/com/meoguri/linkocean/LinkoceanApplication.java
  src/main/java/com/meoguri/linkocean/configuration/security/WebConfiguration.java
  src/main/java/com/meoguri/linkocean/configuration/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/meoguri/linkocean/configuration/security/oauth/SessionUser.java
  src/main/java/com/meoguri/linkocean/infrastructure/s3/S3Config.java
  src/main/java/com/meoguri/linkocean/infrastructure/s3/S3Uploader.java
  src/main/resources/db/migration/V014__Create_session_tables.sql
Labels: 로그인

#74 [LO-51] Profile 등록 API 개발, 테스트 & /login/success API 테스트 작성
  src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
  src/main/java/com/meoguri/linkocean/controller/profile/dto/CreateProfileRequest.java
  src/main/java/com/meoguri/linkocean/controller/user/LoginController.java
  src/main/java/com/meoguri/linkocean/controller/user/dto/LoginSuccessResponse.java
  src/test/java/com/meoguri/linkocean/controller/BaseControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/user/LoginControllerTest.java
Labels: 로그인
