Repository prgrms-web-devcourse/Team-Meoguri-Linkocean-BE, pull requests merged in 2022-09, with the labels that each got.

#208 [LO-205] 프로필 도메인 cqrs 구조 잡기
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/notification/entity/Notification.java
  src/main/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/command/persistence/CustomProfileRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/command/persistence/FindProfileByIdQuery.java
  src/main/java/com/meoguri/linkocean/domain/profile/command/persistence/ProfileRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/command/service/FavoriteServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/command/service/FollowServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/command/service/ProfileServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteBookmarkIds.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategories.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Follow.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
  src/main/java/com/meoguri/linkocean/domain/profile/query/persistence/CustomProfileQueryRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/query/persistence/CustomProfileQueryRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/query/persistence/ProfileQueryRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/query/service/ProfileQueryService.java
  src/main/java/com/meoguri/linkocean/domain/profile/query/service/ProfileQueryServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/user/entity/User.java
  src/main/java/com/meoguri/linkocean/domain/user/service/UserService.java
  src/main/java/com/meoguri/linkocean/domain/user/service/UserServiceImpl.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/command/persistence/CustomProfileRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/command/persistence/FindProfileByIdQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/entity/ProfileTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/query/persistence/CustomProfileQueryRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/query/persistence/ProfileQueryRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/query/service/ProfileQueryServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/user/service/UserServiceImplTest.java
  src/test/java/com/meoguri/linkocean/test/support/domain/entity/BaseEntityTest.java
  src/test/java/com/meoguri/linkocean/test/support/domain/persistence/BasePersistenceTest.java
Labels: 프로필, 리팩토링

#209 [LO-206] 북마크 생성 정책 변경
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByUrlQuery.java
  src/main/resources/db/migration/V021__Alter_bookmark.sql
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByLinkQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/command/service/FavoriteServiceImplTest.java
  src/test/java/com/meoguri/linkocean/test/support/domain/service/BaseServiceTest.java
Labels: 북마크

#210 [LO-208] 링크 메타데이터 정책 변경
  src/main/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/GetLinkMetadata.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/dto/GetLinkMetadataResult.java
  src/main/java/com/meoguri/linkocean/infrastructure/jsoup/JsoupGetLinkMetadataService.java
  src/main/java/com/meoguri/linkocean/infrastructure/jsoup/JsoupLinkMetadataService.java
  src/test/java/com/meoguri/linkocean/DependencyRuleTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
  src/test/java/com/meoguri/linkocean/infrastructure/jsoup/JsoupGetLinkMetadataServiceTest.java
Labels: 리팩토링, 링크메타데이터

#211 [LO-209] Bookmark 도메인 jsoup 의존 없애기
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetBookmarksResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetDetailedBookmarkResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetFeedBookmarksResponse.java
  src/main/java/com/meoguri/linkocean/controller/common/Default.java
  src/main/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
Labels: 북마크, 리팩토링

#212 [LO-210] s3uploader DIP
  src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
  src/main/java/com/meoguri/linkocean/domain/profile/command/service/ProfileImageUploader.java
  src/main/java/com/meoguri/linkocean/infrastructure/s3/S3ProfileImageUploader.java
  src/test/java/com/meoguri/linkocean/DependencyRuleTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
Labels: 리팩토링

#214 [LO-211] 북마크 상세 조회 버그 해결
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
Labels: 북마크, 리팩토링, 버그

#215 [LO-212] 링크 메타데이터 동기화 버그 해결
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
Labels: 링크메타데이터, 버그

#216 [LO-214] 서비스 테스트 @Transactional 제거하기
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/LinkMetadata.java
  src/main/java/com/meoguri/linkocean/domain/notification/entity/Notification.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
  src/main/java/com/meoguri/linkocean/domain/tag/entity/Tag.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/command/service/FavoriteServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/query/service/ProfileQueryServiceImplTest.java
  src/test/java/com/meoguri/linkocean/test/support/db/DatabaseCleanup.java
  src/test/java/com/meoguri/linkocean/test/support/db/DatabaseCleanupTest.java
  src/test/java/com/meoguri/linkocean/test/support/domain/service/BaseServiceTest.java
  src/test/java/com/meoguri/linkocean/test/support/domain/service/ServiceTest.java
Labels: 리팩토링

#217 [LO-215] 컨트롤러 테스트 @Transactional 제거 & 컨밴션에 맞게 리팩토링
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/CategoryControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/ReactionControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/notification/NotificationControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/profile/FavoriteControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/profile/FollowControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/user/LoginControllerTest.java
  src/test/java/com/meoguri/linkocean/test/support/controller/BaseControllerTest.java
  src/test/java/com/meoguri/linkocean/test/support/controller/ControllerTest.java
Labels: 리팩토링

#218 [LO-217] configuration, controller, profile 영속성 코드 통일
  src/main/java/com/meoguri/linkocean/annotation/Query.java
  src/main/java/com/meoguri/linkocean/configuration/SecurityConfiguration.java
  src/main/java/com/meoguri/linkocean/configuration/WebConfiguration.java
  src/main/java/com/meoguri/linkocean/configuration/aop/CustomLoggingAop.java
  src/main/java/com/meoguri/linkocean/configuration/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/meoguri/linkocean/configuration/security/jwt/JwtProvider.java
  src/main/java/com/meoguri/linkocean/configuration/security/jwt/SecurityUser.java
  src/main/java/com/meoguri/linkocean/controller/CustomRestControllerAdvice.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetBookmarksResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetDetailedBookmarkResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetFeedBookmarksResponse.java
  src/main/java/com/meoguri/linkocean/controller/common/Default.java
  src/main/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataController.java
  src/main/java/com/meoguri/linkocean/controller/profile/dto/GetDetailedProfileResponse.java
  src/main/java/com/meoguri/linkocean/controller/profile/dto/GetProfileTagsResponse.java
  src/main/java/com/meoguri/linkocean/controller/user/LoginController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/query/persistence/CustomProfileQueryRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/util/querydsl/CustomPath.java
  src/main/java/com/meoguri/linkocean/util/querydsl/Join.java
  src/main/java/com/meoguri/linkocean/util/querydsl/JoinInfoBuilder.java
  src/main/java/com/meoguri/linkocean/util/querydsl/Querydsl4RepositorySupport.java
  src/test/java/com/meoguri/linkocean/DependencyRuleTest.java
  src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
Labels: 리팩토링

#219 [LO-218] 내 프로필 조회 태그 데이터 버그 해결
  docker-compose.yml
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/util/querydsl/CustomPath.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/test/support/domain/persistence/BasePersistenceTest.java
  src/test/java/com/meoguri/linkocean/test/support/domain/service/BaseServiceTest.java
  src/test/java/com/meoguri/linkocean/test/support/logging/p6spy/P6spyLogMessageFormatConfiguration.java
Labels: 태그, 버그

#221 [LO-220] 다른 사람 북마크 목록 조회 태그 필터링 버그 해결
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/resources/db/migration/V022__Alter_tag.sql
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/tag/persistence/TagRepositoryTest.java
  src/test/java/com/meoguri/linkocean/test/support/domain/persistence/BasePersistenceTest.java
  src/test/resources/application.yml
Labels: 북마크, 버그

#222 [LO-222] 북마크 오픈타입 정책 변경
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/vo/OpenType.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/BookmarkFindCond.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/notification/NotificationControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/query/persistence/ProfileQueryRepositoryTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/BookmarkRestDocsTest.java
Labels: 북마크

#224 [LO-224] 링크 메타데이터 동기화 버그 해결
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
Labels: 링크메타데이터, 버그

#225 [LO-223] follow 에서 id 만 가지게 하기
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Follow.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
  src/main/java/com/meoguri/linkocean/domain/profile/query/persistence/CustomProfileQueryRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/query/persistence/ProfileQueryRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/query/service/ProfileQueryServiceImpl.java
  src/test/java/com/meoguri/linkocean/domain/profile/query/persistence/CustomProfileQueryRepositoryImplTest.java
Labels: 팔로우, 프로필, 리팩토링

#234 [LO-232] 배포, 운영 CI-CD 수정
  .github/workflows/dev-ci-cd.yml
  .github/workflows/prod-ci-cd.yml
Labels: 버그
