Repository prgrms-web-devcourse/Team-Meoguri-Linkocean-BE, pull requests merged in 2022-08, with the labels that each got.

#76 [LO-90] 북마크 컨트롤러
  build.gradle
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/TagController.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetBookmarkResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetBookmarksResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetFeedBookmarksResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetMyTagsResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/RegisterBookmarkRequest.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/UpdateBookmarkRequest.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/support/GetBookmarkQueryParams.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/support/GetBookmarkQueryParamsArgumentResolver.java
  src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
  src/main/java/com/meoguri/linkocean/controller/user/LoginController.java
  src/main/java/com/meoguri/linkocean/controller/user/dto/LoginSuccessResponse.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/BookmarkByUsernameSearchCond.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/FeedBookmarksSearchCond.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetBookmarkResult.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetBookmarksResult.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetFeedBookmarksResult.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/MyBookmarkSearchCond.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/RegisterBookmarkCommand.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/UpdateBookmarkCommand.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImplTest.java
Labels: 북마크

#78 [LO-93] vo 패키지 제거
  src/main/java/com/meoguri/linkocean/configuration/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/LinkMetadata.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/Url.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByUrlQuery.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/persistence/LinkMetadataRepository.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/user/entity/Email.java
  src/main/java/com/meoguri/linkocean/domain/user/entity/User.java
  src/main/java/com/meoguri/linkocean/domain/user/repository/UserRepository.java
  src/test/java/com/meoguri/linkocean/configuration/security/oauth/OAuthAttributesTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/entity/LinkMetadataTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/entity/UrlTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/LinkMetadataRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/user/entity/EmailTest.java
  src/test/java/com/meoguri/linkocean/domain/user/entity/UserTest.java
  src/test/java/com/meoguri/linkocean/domain/user/repository/UserRepositoryTest.java
Labels: 세팅

#79 [LO-52] 내정보 조회(사용자 태그목록, 카테고리 목록 추가) 외 다양한 작업들
  src/main/java/com/meoguri/linkocean/configuration/WebConfiguration.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/RegisterBookmarkRequest.java
  src/main/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataController.java
  src/main/java/com/meoguri/linkocean/controller/linkmetadata/dto/LinkMetadataTitleResponse.java
  src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
  src/main/java/com/meoguri/linkocean/controller/profile/dto/GetMyProfileResponse.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/CategoryService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategory.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/dto/GetMyProfileResult.java
  src/test/java/com/meoguri/linkocean/controller/BaseControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/category/CategoryControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/user/LoginControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/TagServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
Labels: 프로필

#81 [LO-91] 리액션 요청 API
  src/main/java/com/meoguri/linkocean/controller/bookmark/ReactionController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Reaction.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/ReactionControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImplTest.java
Labels: 리액션

#84 [LO-98] 내 프로필 조회 category NPE 해결
  src/main/java/com/meoguri/linkocean/configuration/WebConfiguration.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImpl.java
  src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImplTest.java
Labels: 프로필

#85 [LO-97] 북마크 제목, 메모, 카테고리 Null인 경우 NPE 이슈 해결
  src/main/java/com/meoguri/linkocean/configuration/DateFormatConfig.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetBookmarkResponse.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
Labels: 북마크

#86 [LO-91] 리액션 API 리팩토링
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/ReactionControllerTest.java
Labels: 리액션

#87 [LO-99] 팔로우/언팔로우 컨트롤러
  src/main/java/com/meoguri/linkocean/configuration/WebConfiguration.java
  src/main/java/com/meoguri/linkocean/controller/CustomRestControllerAdvice.java
  src/main/java/com/meoguri/linkocean/controller/IndexController.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/TagController.java
  src/main/java/com/meoguri/linkocean/controller/category/CategoryController.java
  src/main/java/com/meoguri/linkocean/controller/common/ListResponse.java
  src/main/java/com/meoguri/linkocean/controller/common/ListResponseJsonSerializer.java
  src/main/java/com/meoguri/linkocean/controller/common/SimpleIdResponse.java
  src/main/java/com/meoguri/linkocean/controller/profile/FollowController.java
  src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
  src/main/java/com/meoguri/linkocean/controller/profile/dto/GetMyProfileResponse.java
  src/test/java/com/meoguri/linkocean/controller/BaseControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/ReactionControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/category/CategoryControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/profile/FollowControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/user/LoginControllerTest.java
Labels: 팔로우

#88 [LO-101] rename GetBookmarkXXX -> GetDetailedBookmarkXXX
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetDetailedBookmarkResponse.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetDetailedBookmarkResult.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
Labels: 리팩토링

#91 [LO-104] 북마크 상세 조회 컨트롤러 & 서비스 개발
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetDetailedBookmarkResponse.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetDetailedBookmarkResult.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
Labels: 북마크

#92 [LO-66] 공유 알림 생성, 알림 조회 서비스
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/notification/entity/noti/BookmarkNoti.java
  src/main/java/com/meoguri/linkocean/domain/notification/entity/noti/ProfileNoti.java
  src/main/java/com/meoguri/linkocean/domain/notification/service/NotificationService.java
  src/main/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/CheckIsFollowQuery.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/FollowServiceImpl.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/CheckIsFollowQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepositoryTest.java
Labels: 알림

#95 [LO-108] 팔로워/팔로이 목록 조회 컨트롤러 테스트
  src/main/java/com/meoguri/linkocean/configuration/WebConfiguration.java
  src/main/java/com/meoguri/linkocean/controller/CustomRestControllerAdvice.java
  src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
  src/main/java/com/meoguri/linkocean/controller/profile/support/ProfileSearchTab.java
  src/main/java/com/meoguri/linkocean/controller/profile/support/ProfileSearchTabConverterFactory.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileService.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/dto/ProfileSearchCond.java
  src/test/java/com/meoguri/linkocean/controller/BaseControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImplTest.java
Labels: 프로필

#96 [LO-67] 공유 알림 생성, 알림 목록 조회 컨트롤러
  src/main/java/com/meoguri/linkocean/controller/notification/NotificationController.java
  src/main/java/com/meoguri/linkocean/controller/notification/dto/ShareNotificationRequest.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/notification/service/NotificationService.java
  src/main/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImpl.java
  src/test/java/com/meoguri/linkocean/controller/notification/NotificationControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImplTest.java
Labels: 알림

#97 [LO-107] 내 북마크 목록 조회 서비스 & 컨트롤러 개발
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/TagController.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetBookmarksResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetDetailedBookmarkResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetMyTagsResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/support/GetBookmarkQueryParams.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/support/GetBookmarkQueryParamsArgumentResolver.java
  src/main/java/com/meoguri/linkocean/controller/category/CategoryController.java
  src/main/java/com/meoguri/linkocean/controller/common/PageResponse.java
  src/main/java/com/meoguri/linkocean/controller/common/PageResponseJsonSerializer.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/FindBookmarksDefaultCond.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetBookmarksResult.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/MyBookmarkSearchCond.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/PageResult.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/category/CategoryControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
Labels: 북마크

#98 [LO-91] 리액션 요청 API
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImplTest.java
Labels: 리액션

#99 [LO-110] 다른 사람 북마크 조회 & 피드 북마크 조회 컨트롤러 껍데기 개발
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetFeedBookmarksResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/support/GetBookmarkQueryParams.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/BookmarkByUsernameSearchCond.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/OtherBookmarkSearchCond.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
Labels: 북마크

#100 [LO-111] Profile update API 개발
  src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
  src/main/java/com/meoguri/linkocean/controller/profile/dto/UpdateProfileRequest.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
  src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
Labels: 프로필

#101 [LO-109] 구조 리팩토링
  src/main/java/com/meoguri/linkocean/configuration/WebConfiguration.java
  src/main/java/com/meoguri/linkocean/configuration/resolver/GetBookmarkQueryParams.java
  src/main/java/com/meoguri/linkocean/configuration/resolver/GetBookmarkQueryParamsArgumentResolver.java
  src/main/java/com/meoguri/linkocean/configuration/resolver/GetProfileQueryParams.java
  src/main/java/com/meoguri/linkocean/configuration/resolver/GetProfileQueryParamsArgumentResolver.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/CategoryController.java
  src/main/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataController.java
  src/main/java/com/meoguri/linkocean/controller/linkmetadata/dto/LinkMetadataTitleResponse.java
  src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
  src/main/java/com/meoguri/linkocean/controller/profile/dto/GetMyProfileResponse.java
  src/main/java/com/meoguri/linkocean/controller/profile/support/ProfileSearchTab.java
  src/main/java/com/meoguri/linkocean/controller/profile/support/ProfileSearchTabConverterFactory.java
  src/main/java/com/meoguri/linkocean/controller/user/LoginController.java
  src/main/java/com/meoguri/linkocean/controller/user/dto/LoginResponse.java
  src/main/java/com/meoguri/linkocean/controller/user/dto/LoginSuccessReponse.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/CategoryService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/TagService.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/TagServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/dto/GetMyTagsResult.java
  src/test/java/com/meoguri/linkocean/common/DependencyRuleTest.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/CategoryControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/TagServiceImplTest.java
Labels: 리팩토링

#102 [LO-57] 북마크 삭제 API 개발
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
Labels: 북마크

#104 [LO-113] queryParam 한글 이슈
  src/test/java/com/meoguri/linkocean/controller/BaseControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
Labels: 프로필, 리팩토링

#105 [LO-112] 다른 사람 북마크 조회 서비스 개발 & 링크 메타데이터 정책 변경
  src/main/java/com/meoguri/linkocean/configuration/resolver/GetBookmarkQueryParams.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/FindBookmarksDefaultCond.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/MyBookmarkSearchCond.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/OtherBookmarkSearchCond.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
Labels: 북마크

#106 [LO-115] 내 북마크 조회 리팩토링
  src/main/java/com/meoguri/linkocean/configuration/resolver/GetBookmarkQueryParams.java
  src/main/java/com/meoguri/linkocean/configuration/resolver/GetBookmarkQueryParamsArgumentResolver.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/BookmarkFindCond.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/FindBookmarksDefaultCond.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/MyBookmarkSearchCond.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/OtherBookmarkSearchCond.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/CheckIsFavoriteQuery.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/dto/ProfileFindCond.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
  src/main/java/com/meoguri/linkocean/util/Querydsl4RepositorySupport.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImplTest.java
Labels: 북마크, 리팩토링

#107 [LO-116] 다른 사람 북마크 목록 조회 컨트롤러 개발
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/test/java/com/meoguri/linkocean/controller/BaseControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
Labels: 북마크

#110 [LO-118] joinIf 강화, 북마크 조회 통합 초벌
  README.md
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/UltimateBookmarkFindCond.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/util/JoinInfo.java
  src/main/java/com/meoguri/linkocean/util/JoinInfoListBuilder.java
  src/main/java/com/meoguri/linkocean/util/QueryDslUtil.java
Labels: 세팅

#113 [LO-122] 로그 레밸 설정 & 북마크 상세 조회 이슈 해결
  src/main/java/com/meoguri/linkocean/controller/CustomRestControllerAdvice.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
Labels: 북마크, 세팅

#112 [LO-121] Bookmark register, update addTag 방식 통일 및 테스트 파급효과 처리
  src/main/java/com/meoguri/linkocean/configuration/WebConfiguration.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/TagServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
Labels: 북마크, 리팩토링

#114 [LO-120] 궁극의 북마크 조회 영속성 계층
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/UltimateBookmarkFindCond.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/util/Join.java
  src/main/java/com/meoguri/linkocean/util/JoinInfoBuilder.java
  src/main/java/com/meoguri/linkocean/util/JoinInfoListBuilder.java
  src/main/java/com/meoguri/linkocean/util/QueryDslUtil.java
  src/main/java/com/meoguri/linkocean/util/Querydsl4RepositorySupport.java
  src/test/java/com/meoguri/linkocean/common/Ultimate.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
Labels: 북마크, 리팩토링

#115 [LO-123] BookmarkStatus 추가, 삭제 시 Status.REMOVED로 변경
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/CategoryController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/vo/BookmarkStatus.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/vo/Category.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/vo/OpenType.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/UltimateBookmarkFindCond.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategory.java
  src/main/resources/db/migration/V001__Create_bookmark.sql
  src/main/resources/db/migration/V013__Create_session_tables.sql
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategoryTest.java
Labels: 북마크, 리팩토링

#117 [LO-124] 프로필 도메인 userId -> profileId 수정 & custom assertion 도입
  src/main/java/com/meoguri/linkocean/configuration/resolver/GetProfileQueryParams.java
  src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
  src/main/java/com/meoguri/linkocean/controller/profile/dto/UpdateProfileRequest.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/CategoryService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileService.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/TagService.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/TagServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/dto/ProfileSearchCond.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/dto/UpdateProfileCommand.java
  src/test/java/com/meoguri/linkocean/common/LinkoceanAssert.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByLinkQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/entity/ProfileTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/FollowServiceImplTest.java
Labels: 프로필, 리팩토링

#121 [LO-128] 중복 url 확인 로직 리팩토링, 픽스/ joinIf on 절 매번 동작 할 수 있도록 변경
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionQuery.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/util/Join.java
  src/main/java/com/meoguri/linkocean/util/JoinInfoBuilder.java
  src/main/java/com/meoguri/linkocean/util/Querydsl4RepositorySupport.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
Labels: 리팩토링

#123 [LO-130] 북마크 모든 조회 where 절에 status 처리
  build.gradle
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetDetailedBookmarkResponse.java
  src/main/java/com/meoguri/linkocean/controller/common/CustomDateFormatter.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Follow.java
  src/test/java/com/meoguri/linkocean/common/DependencyRuleTest.java
  src/test/java/com/meoguri/linkocean/controller/BaseControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/ReactionControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/entity/FollowTest.java
Labels: 북마크

#124 [LO-131] 1. 테스트시 링크 메타데이터 모킹 2. 북마크 상세조회 응답 bookmarkId 추가
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetDetailedBookmarkResponse.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetDetailedBookmarkResult.java
  src/test/java/com/meoguri/linkocean/controller/BaseControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
Labels: 리팩토링

#126 [LO-134] openType 적용 필터링 부활, migration 발생
  src/main/java/com/meoguri/linkocean/configuration/converter/OpenTypeConverter.java
  src/main/java/com/meoguri/linkocean/configuration/resolver/GetBookmarkQueryParamsArgumentResolver.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/vo/OpenType.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionQuery.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/UltimateBookmarkFindCond.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/CheckIsFollowQuery.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
  src/main/resources/db/migration/V001__Create_bookmark.sql
  src/main/resources/db/migration/V002__Create_bookmark_tag.sql
  src/main/resources/db/migration/V003__Create_favorite_category.sql
  src/main/resources/db/migration/V004__Create_follow.sql
  src/main/resources/db/migration/V007__Create_reaction.sql
  src/main/resources/db/migration/V009__Create_users.sql
  src/main/resources/db/migration/V010__Create_favorite.sql
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/FavoriteControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/ReactionControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/GetBookmarkByIdQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/CheckIsFollowQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepositoryTest.java
Labels: 북마크

#127 [LO-133] 프로필 목록 조회 영속성 계층 리팩토링
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/dto/UltimateProfileFindCond.java
  src/main/java/com/meoguri/linkocean/util/Querydsl4RepositorySupport.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImplTest.java
Labels: 프로필, 리팩토링

#128 [LO-136] 피드 북마크 조회 + a
  build.gradle
  src/main/java/com/meoguri/linkocean/configuration/resolver/GetBookmarkQueryParams.java
  src/main/java/com/meoguri/linkocean/controller/CustomRestControllerAdvice.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetDetailedBookmarkResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetFeedBookmarksResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/RegisterBookmarkRequest.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/BookmarkFindCond.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/FeedBookmarksSearchCond.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetDetailedBookmarkResult.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetFeedBookmarksResult.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/LinkMetadataResult.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/CheckIsFavoriteQuery.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/CheckIsFollowQuery.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
  src/main/java/com/meoguri/linkocean/util/Querydsl4RepositorySupport.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/CheckIsFollowQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
Labels: 북마크

#130 [LO-140] 알림 더미데이터 말기
  src/main/java/com/meoguri/linkocean/controller/controller/NotificationController.java
  src/main/java/com/meoguri/linkocean/controller/controller/dto/NotificationResponse.java
Labels: 알림

#133 [LO-141] 북마크 피드조회 서비스, 영속성 테스트
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetBookmarksResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetDetailedBookmarkResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetFeedBookmarksResponse.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/vo/Category.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/test/java/com/meoguri/linkocean/controller/BaseControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
Labels: 북마크

#134 [LO-142] 프로필 목록 조회 서비스 계층 리팩토링
  README.md
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/CheckIsFollowQuery.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileService.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
Labels: 프로필, 리팩토링

#136 [LO-145] 더미데이터 마는 sql script
  src/main/resources/db/data/insert_bookmark.sql
  src/main/resources/db/data/insert_linkmetadata.sql
Labels: 세팅

#138 [LO-146] 비즈니스로직 예외 처리는 db 조회를 하자
  src/main/java/com/meoguri/linkocean/controller/CustomRestControllerAdvice.java
  src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/ProfileRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/FollowServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/TagService.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/TagServiceImpl.java
  src/main/java/com/meoguri/linkocean/exception/Preconditions.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/ProfileRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/TagServiceImplTest.java
Labels: 리팩토링

#135 [LO-144] 즐겨찾기 로직 수정
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/BookmarkFindCond.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
Labels: 북마크

#137 [LO-143] Logging AOP 개발
  build.gradle
  src/main/java/com/meoguri/linkocean/configuration/logger/LinkoceanLogAop.java
  src/main/java/com/meoguri/linkocean/configuration/security/jwt/SecurityUser.java
  src/test/java/com/meoguri/linkocean/LinkoceanApplicationTests.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
Labels: 세팅

#141 [LO-148] 공유 알림 생성, 조회
  build.gradle
  src/main/java/com/meoguri/linkocean/configuration/FlywayConfiguration.java
  src/main/java/com/meoguri/linkocean/configuration/WebConfiguration.java
  src/main/java/com/meoguri/linkocean/configuration/aop/CustomLoggingAop.java
  src/main/java/com/meoguri/linkocean/controller/notification/NotificationController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/notification/entity/Notification.java
  src/main/java/com/meoguri/linkocean/domain/notification/entity/NotificationType.java
  src/main/java/com/meoguri/linkocean/domain/notification/persistence/NotificationRepository.java
  src/main/java/com/meoguri/linkocean/domain/notification/service/NotificationService.java
  src/main/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/notification/service/dto/ShareNotificationCommand.java
  src/main/resources/db/migration/V013__Create_notification.sql
  src/main/resources/db/migration/V014__Alter_bookmark.sql
  src/test/java/com/meoguri/linkocean/common/Assertions.java
  src/test/java/com/meoguri/linkocean/controller/notification/NotificationControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByLinkQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/LinkMetadataRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/entity/FollowTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/entity/ProfileTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/FollowServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/TagServiceImplTest.java
  src/test/resources/application.yml
  src/test/resources/db/tests/V001__Create_jsonb_alias.sql
Labels: 알림

#146 [LO-150] 북마크 오픈타입 이슈 해결 (이미 해결됨?!)
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
Labels: 북마크

#148 [LO-151] 에러 로그 상세화, 피드 북마크 즐겨찾기 응답 버그 수정 favoriteService -> profileId 사용
  src/main/java/com/meoguri/linkocean/configuration/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/meoguri/linkocean/configuration/security/jwt/JwtProvider.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/FavoriteController.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetFeedBookmarksResponse.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/vo/Category.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/FindBookmarkByIdQuery.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByUrlQuery.java
  src/main/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/FindProfileByIdQuery.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/FindProfileByUserIdQuery.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/FollowServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/user/repository/FindUserByIdQuery.java
  src/main/java/com/meoguri/linkocean/exception/LinkoceanRuntimeException.java
  src/main/java/com/meoguri/linkocean/exception/Preconditions.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
Labels: 리팩토링

#149 [LO-136] reaction 동시성
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImplTest.java
Labels: 리액션

#153 [LO-153] 자질구래 리팩토링, 제거대상 제거
  .github/workflows/test-every-pull-request.yml
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/controller/notification/NotificationController.java
  src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/FindProfileByUserIdQuery.java
  src/main/java/com/meoguri/linkocean/infrastructure/jsoup/SearchLinkMetadataResult.java
  src/main/java/com/meoguri/linkocean/util/Querydsl4RepositorySupport.java
  src/test/java/com/meoguri/linkocean/controller/notification/NotificationControllerTest.java
Labels: 리팩토링

#154 [LO-154] RestDocs 세팅 추가
  build.gradle
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/CategoryControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/FavoriteControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/ReactionControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/notification/NotificationControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/profile/FollowControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/support/BaseControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/support/RestDocsConfig.java
  src/test/java/com/meoguri/linkocean/controller/support/RestDocsTestSupport.java
  src/test/java/com/meoguri/linkocean/controller/user/LoginControllerTest.java
Labels: 세팅

#155 [LO-156] login, follow, notification, linkMetadata, profile restdocs 추가
  build.gradle
  docs/asciidoc/FOLLOW-API.adoc
  docs/asciidoc/LINKMETADATA-API.adoc
  docs/asciidoc/LOGIN-API.adoc
  docs/asciidoc/NOTIFICATION-API.adoc
  docs/asciidoc/PROFILE_API.adoc
  docs/asciidoc/index.adoc
  src/test/java/com/meoguri/linkocean/controller/restdocs/FollowDocsController.java
  src/test/java/com/meoguri/linkocean/controller/restdocs/LinkMetadataDocsController.java
  src/test/java/com/meoguri/linkocean/controller/restdocs/LoginDocsController.java
  src/test/java/com/meoguri/linkocean/controller/restdocs/NotificationDocsController.java
  src/test/java/com/meoguri/linkocean/controller/restdocs/ProfileDocsController.java
Labels: 문서

#158 [LO-159] Reaction & Favorite RestDocs 추가
  src/test/java/com/meoguri/linkocean/controller/restdocs/FavoriteDocsController.java
  src/test/java/com/meoguri/linkocean/controller/restdocs/ReactionDocsController.java
Labels: 문서

#159 [LO-158] 링크 메타데이터 저장시 http(s) & www 제거하는 로직 제거하기
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/Link.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/LinkMetadata.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/entity/LinkTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByLinkQueryTest.java
Labels: 링크, 리팩토링

#156 [LO-157] 링크 메타데이터 제목 조회 API 수정
  src/main/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataController.java
  src/test/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataControllerTest.java
Labels: 북마크

#161 [LO-161] follow, favorite 서비스 로직 통일, 조회로 중복 검증
  src/main/java/com/meoguri/linkocean/controller/profile/FollowController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/FollowService.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/FollowServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/dto/FollowCommand.java
  src/main/java/com/meoguri/linkocean/exception/Preconditions.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/FollowServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImplTest.java
Labels: 리팩토링

#164 [LO-163] 소셜 로그인 타입에 GITHUB 추가
  src/main/java/com/meoguri/linkocean/configuration/security/jwt/JwtProvider.java
  src/main/java/com/meoguri/linkocean/controller/user/LoginController.java
  src/main/java/com/meoguri/linkocean/domain/user/entity/vo/OAuthType.java
  src/test/java/com/meoguri/linkocean/domain/user/entity/UserTest.java
  src/test/java/com/meoguri/linkocean/domain/user/service/UserServiceImplTest.java
Labels: 로그인

#166 [LO-164] 컨트롤러 페이저블 파라미터로 사용 및 configuration.resolver 패키지 공중분해
  src/main/java/com/meoguri/linkocean/configuration/WebConfiguration.java
  src/main/java/com/meoguri/linkocean/configuration/resolver/GetBookmarkQueryParams.java
  src/main/java/com/meoguri/linkocean/configuration/resolver/GetBookmarkQueryParamsArgumentResolver.java
  src/main/java/com/meoguri/linkocean/configuration/resolver/GetProfileQueryParams.java
  src/main/java/com/meoguri/linkocean/configuration/resolver/GetProfileQueryParamsArgumentResolver.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
  src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/converter/OpenTypeConverter.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/BookmarkFindCond.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/GetBookmarkQueryParams.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
  src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/TagRepositoryTest.java
Labels: 리팩토링

#167 [LO-165] rename fields in entity
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Favorite.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/TagServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/RegisterBookmarkCommand.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/UpdateBookmarkCommand.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/CheckIsFavoriteQuery.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/FollowServiceImpl.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/FavoriteTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepositoryTest.java
Labels: 리팩토링

#169 [LO-168] 리액션 vo 전역적 사용, 리액션 서비스 리팩토링
  src/main/java/com/meoguri/linkocean/controller/bookmark/ReactionController.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetDetailedBookmarkResponse.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Reaction.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/vo/ReactionType.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionQuery.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetDetailedBookmarkResult.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/ReactionCommand.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/ReactionControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/ReactionTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImplTest.java
Labels: 리액션, 리팩토링

#171 [LO-170] S3 적용 개선 1단계
  build.gradle
  src/main/java/com/meoguri/linkocean/infrastructure/s3/S3Uploader.java
  src/test/java/com/meoguri/linkocean/infrastructure/s3/S3UploaderTest.java
Labels: 리팩토링

#172 [LO-171] Favrotie Category : @Entity -> @ElementCollection
  src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategory.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
  src/main/resources/db/migration/V017__Alter_favorite_category.sql
  src/test/java/com/meoguri/linkocean/controller/restdocs/ProfileDocsController.java
  src/test/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/entity/ProfileTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImplTest.java
  src/test/java/com/meoguri/linkocean/infrastructure/s3/S3UploaderTest.java
Labels: 리팩토링

#174 [LO-172] BasePersistenceTest 적용 완료
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Favorite.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionQuery.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/FollowServiceImpl.java
  src/main/java/com/meoguri/linkocean/exception/Preconditions.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/FavoriteTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/TagRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByLinkQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/LinkMetadataRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/CheckIsFollowQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/FindProfileByIdQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/ProfileRepositoryTest.java
  src/test/java/com/meoguri/linkocean/test/support/persistence/BasePersistenceTest.java
Labels: 리팩토링

#175 [LO-173] refactor rest docs test
  .github/workflows/test-every-pull-request.yml
  build.gradle
  docs/asciidoc/BOOKMARK-API.adoc
  docs/asciidoc/CATEGORY-API.adoc
  docs/asciidoc/FOLLOW-API.adoc
  docs/asciidoc/LINKMETADATA-API.adoc
  docs/asciidoc/LOGIN-API.adoc
  docs/asciidoc/NOTIFICATION-API.adoc
  docs/asciidoc/PROFILE_API.adoc
  docs/asciidoc/index.adoc
  src/docs/asciidoc/api/Boomark-API.adoc
  src/docs/asciidoc/api/Category-API.adoc
  src/docs/asciidoc/api/Favorite-API.adoc
  src/docs/asciidoc/api/Follow-API.adoc
  src/docs/asciidoc/api/LinkMetadata-API.adoc
  src/docs/asciidoc/api/Login-API.adoc
  src/docs/asciidoc/api/Notification-API.adoc
  src/docs/asciidoc/api/Profile_API.adoc
  src/docs/asciidoc/api/Reaction-API.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/meoguri/linkocean/configuration/WebConfiguration.java
  src/main/resources/static/health.html
  src/test/java/com/meoguri/linkocean/controller/bookmark/CategoryControllerTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/BookmarkRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/CategoryRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/FavoriteRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/FollowRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/LinkMetadataRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/LoginRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/NotificationRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/ProfileRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/ReactionRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/RestDocs.java
  src/test/java/com/meoguri/linkocean/test/support/controller/RestDocsTestSupport.java
Labels: 문서, 리팩토링

#178 [LO-177] 사용자 쪽 리팩토링
  src/main/java/com/meoguri/linkocean/configuration/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/meoguri/linkocean/configuration/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/meoguri/linkocean/controller/user/LoginController.java
  src/main/java/com/meoguri/linkocean/domain/user/service/UserService.java
  src/main/java/com/meoguri/linkocean/domain/user/service/UserServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/user/service/dto/GetUserResult.java
  src/test/java/com/meoguri/linkocean/DependencyRuleTest.java
  src/test/java/com/meoguri/linkocean/domain/user/service/UserServiceImplTest.java
  src/test/java/com/meoguri/linkocean/test/support/service/BaseServiceTest.java
Labels: 리팩토링

#177 [LO-176] 즐겨찾기 북마크 확인 로직 프로필 도메인에 응집
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteBookmarkIds.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategories.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/CategoryControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/entity/ProfileTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/ProfileRepositoryTest.java
  src/test/java/com/meoguri/linkocean/test/support/common/Fixture.java
Labels: 프로필, 리팩토링

#180 [LO-179] 링크메타데이터 서비스 리팩토링, BaseTest 적용,
  src/main/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataController.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataService.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/scheduler/LinkMetadataSynchronizeSchedulerTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
  src/test/java/com/meoguri/linkocean/test/support/service/BaseServiceTest.java
Labels: 링크, 리팩토링

#182 [LO-181] 북마크 목록 조회 카운트 쿼리 최적화
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/util/querydsl/CustomPath.java
  src/main/java/com/meoguri/linkocean/util/querydsl/Join.java
  src/main/java/com/meoguri/linkocean/util/querydsl/JoinInfoBuilder.java
  src/main/java/com/meoguri/linkocean/util/querydsl/Querydsl4RepositorySupport.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
Labels: 북마크, 리팩토링

#184 [LO-183] Local Test DB 이름 변경
  env/mysql.env
  src/test/resources/application.yml
Labels: 세팅

#181 [LO-180] 서비스 테스트 코드 리팩토링
  src/main/java/com/meoguri/linkocean/annotation/Query.java
  src/main/java/com/meoguri/linkocean/configuration/aop/CustomLoggingAop.java
  src/main/java/com/meoguri/linkocean/controller/notification/dto/NotificationResponse.java
  src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionService.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategories.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
  src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTagTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/TagServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/entity/ProfileTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/CheckIsFollowQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/FindProfileByIdQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/ProfileRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/FollowServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/user/service/UserServiceImplTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/ProfileRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/support/common/Fixture.java
  src/test/java/com/meoguri/linkocean/test/support/persistence/BasePersistenceTest.java
  src/test/java/com/meoguri/linkocean/test/support/service/BaseServiceTest.java
Labels: 리팩토링

#183 [LO-182] WIP @Entity 북마크.리액션 deprecation -> @ElementCollection 프로필.리액션
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Reaction.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionQuery.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteBookmarkIds.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Reaction.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Reactions.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/FindProfileByIdQuery.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/ProfileRepository.java
  src/main/java/com/meoguri/linkocean/util/querydsl/CustomPath.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
  src/test/java/com/meoguri/linkocean/test/support/persistence/BasePersistenceTest.java
Labels: 리액션

#187 [LO-184] 리액션 엔티티 제거 끝
  src/main/java/com/meoguri/linkocean/configuration/S3Configuration.java
  src/main/java/com/meoguri/linkocean/configuration/WebConfiguration.java
  src/main/java/com/meoguri/linkocean/configuration/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Reaction.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionQuery.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategories.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/Reactions.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/FindProfileByIdQuery.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/ProfileRepository.java
  src/main/resources/db/migration/V019__Alter_reaction.sql
  src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/ReactionTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/entity/ProfileTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/ProfileRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImplTest.java
Labels: 리액션, 리팩토링

#188 [LO-185] 북마크 태그 @ManyToMany 로 처리
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTag.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Tags.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/TagService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/TagServiceImpl.java
  src/main/java/com/meoguri/linkocean/util/querydsl/CustomPath.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTagTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/TagsTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/entity/ProfileTest.java
  src/test/java/com/meoguri/linkocean/test/support/common/Fixture.java
  src/test/java/com/meoguri/linkocean/test/support/persistence/BasePersistenceTest.java
Labels: 북마크, 리팩토링

#190 [LO-187] 프로필 도메인 CQRS 패턴 도입 초벌
  src/main/java/com/meoguri/linkocean/controller/profile/FollowController.java
  src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
  src/main/java/com/meoguri/linkocean/controller/profile/dto/CreateProfileRequest.java
  src/main/java/com/meoguri/linkocean/controller/profile/dto/GetDetailedProfileResponse.java
  src/main/java/com/meoguri/linkocean/controller/profile/dto/GetProfileTagsResponse.java
  src/main/java/com/meoguri/linkocean/controller/profile/dto/GetProfilesResponse.java
  src/main/java/com/meoguri/linkocean/controller/profile/dto/UpdateProfileRequest.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/TagService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/TagServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategories.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/command/FindProfileByIdQuery.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/command/ProfileRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/query/ProfileQueryRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/query/ProfileQueryRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/query/dto/ProfileFindCond.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileService.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/command/FollowService.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/command/FollowServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/command/ProfileService.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/command/ProfileServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/command/dto/RegisterProfileCommand.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/command/dto/UpdateProfileCommand.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/query/ProfileQueryService.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/query/ProfileQueryServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/query/dto/GetDetailedProfileResult.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/query/dto/GetProfileTagsResult.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/query/dto/GetProfilesResult.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/TagServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/command/FindProfileByIdQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/command/ProfileRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/query/ProfileQueryRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/command/FollowServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/command/ProfileServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/query/ProfileQueryServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/user/service/UserServiceImplTest.java
  src/test/java/com/meoguri/linkocean/test/support/persistence/BasePersistenceTest.java
  src/test/java/com/meoguri/linkocean/test/support/service/BaseServiceTest.java
Labels: 프로필, 리팩토링

#191 [LO-188] 태그 도메인 분리, 북마크 좋아요 숫자 업데이트 로직 서비스 -> 영속성
  src/main/java/com/meoguri/linkocean/controller/bookmark/FavoriteController.java
  src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/command/FindProfileByIdQuery.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/command/ProfileRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/query/ProfileQueryRepository.java
  src/main/java/com/meoguri/linkocean/domain/profile/persistence/query/ProfileQueryRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/command/FavoriteService.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/command/FavoriteServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/command/ProfileServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/query/CategoryQueryService.java
  src/main/java/com/meoguri/linkocean/domain/profile/service/query/CategoryQueryServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/tag/entity/Tag.java
  src/main/java/com/meoguri/linkocean/domain/tag/entity/Tags.java
  src/main/java/com/meoguri/linkocean/domain/tag/persistence/TagRepository.java
  src/main/java/com/meoguri/linkocean/domain/tag/service/TagService.java
  src/main/java/com/meoguri/linkocean/domain/tag/service/TagServiceImpl.java
  src/main/java/com/meoguri/linkocean/util/querydsl/Querydsl4RepositorySupport.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/command/ProfileRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/persistence/query/ProfileQueryRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/command/FavoriteServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/query/CategoryQueryServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/service/query/ProfileQueryServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/tag/entity/TagTest.java
  src/test/java/com/meoguri/linkocean/domain/tag/entity/TagsTest.java
  src/test/java/com/meoguri/linkocean/domain/tag/persistence/TagRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/tag/service/TagServiceImplTest.java
  src/test/java/com/meoguri/linkocean/test/support/common/Fixture.java
  src/test/java/com/meoguri/linkocean/test/support/persistence/BasePersistenceTest.java
  src/test/java/com/meoguri/linkocean/test/support/service/BaseServiceTest.java
  src/test/resources/application.yml
Labels: 북마크, 태그

#193 [LO-191] FindProfileByIdQuery function 적용, test sql log pretty
  src/main/java/com/meoguri/linkocean/controller/bookmark/ReactionController.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetDetailedBookmarkResponse.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetDetailedBookmarkResult.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/ReactionCommand.java
  src/main/java/com/meoguri/linkocean/domain/profile/command/entity/Profile.java
  src/main/java/com/meoguri/linkocean/domain/profile/command/entity/Reaction.java
  src/main/java/com/meoguri/linkocean/domain/profile/command/entity/Reactions.java
  src/main/java/com/meoguri/linkocean/domain/profile/command/entity/vo/ReactionType.java
  src/main/java/com/meoguri/linkocean/domain/profile/command/persistence/FindProfileByIdQuery.java
  src/main/java/com/meoguri/linkocean/util/querydsl/CustomPath.java
  src/test/java/com/meoguri/linkocean/controller/bookmark/ReactionControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/command/persistence/ProfileRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/query/persistence/ProfileDaoImplTest.java
  src/test/java/com/meoguri/linkocean/test/support/common/CustomP6spySqlFormat.java
  src/test/java/com/meoguri/linkocean/test/support/common/P6spyLogMessageFormatConfiguration.java
  src/test/java/com/meoguri/linkocean/test/support/controller/BaseControllerTest.java
  src/test/java/com/meoguri/linkocean/test/support/logging/p6spy/P6spyLogMessageFormatConfiguration.java
  src/test/java/com/meoguri/linkocean/test/support/logging/p6spy/SqlFormatOneline.java
  src/test/java/com/meoguri/linkocean/test/support/logging/p6spy/SqlFormatPretty.java
  src/test/java/com/meoguri/linkocean/test/support/persistence/BasePersistenceTest.java
  src/test/java/com/meoguri/linkocean/test/support/service/BaseServiceTest.java
Labels: 리팩토링

#194 [LO-192] 프로필 도메인 관련 코드 살펴보고 짜잘한 리팩토링
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/vo/Category.java
  src/main/java/com/meoguri/linkocean/domain/profile/command/entity/FavoriteBookmarkIds.java
  src/main/java/com/meoguri/linkocean/domain/profile/command/entity/FavoriteCategories.java
  src/main/java/com/meoguri/linkocean/domain/profile/command/entity/Profile.java
  src/main/java/com/meoguri/linkocean/domain/profile/command/entity/Reactions.java
  src/main/java/com/meoguri/linkocean/domain/profile/command/persistence/ProfileRepository.java
  src/test/java/com/meoguri/linkocean/domain/profile/command/service/FavoriteServiceImplTest.java
  src/test/java/com/meoguri/linkocean/test/support/service/BaseServiceTest.java
Labels: 프로필, 리팩토링

#197 [LO-195] 개발 서버 CI/CD 구축
  .github/workflows/dev-ci-cd.yml
Labels: 세팅

#201 [LO-199] Dev CI-CD 포트번호 수정
  .github/workflows/dev-ci-cd.yml
Labels: 세팅

#200 [LO-198] api 문서 jar에 말기
  build.gradle
Labels: 문서, 세팅

#203 [LO-200] 태그/ 북마크 애그리거트 경계 좀 더 나누기
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetBookmarksResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetDetailedBookmarkResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetFeedBookmarksResponse.java
  src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
  src/main/java/com/meoguri/linkocean/controller/profile/dto/GetDetailedProfileResponse.java
  src/main/java/com/meoguri/linkocean/controller/profile/dto/GetProfileTagsResponse.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/vo/TagIds.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/FindUsedTagIdWithCountResult.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetBookmarksResult.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetDetailedBookmarkResult.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetFeedBookmarksResult.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetUsedTagWithCountResult.java
  src/main/java/com/meoguri/linkocean/domain/tag/persistence/TagRepository.java
  src/main/java/com/meoguri/linkocean/domain/tag/service/TagService.java
  src/main/java/com/meoguri/linkocean/domain/tag/service/TagServiceImpl.java
  src/main/java/com/meoguri/linkocean/util/querydsl/CustomPath.java
  src/main/java/com/meoguri/linkocean/util/querydsl/Querydsl4RepositorySupport.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/vo/TagIdsTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/command/entity/ProfileTest.java
  src/test/java/com/meoguri/linkocean/domain/tag/entity/TagsTest.java
  src/test/java/com/meoguri/linkocean/domain/tag/persistence/TagRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/tag/service/TagServiceImplTest.java
  src/test/java/com/meoguri/linkocean/test/support/common/Fixture.java
  src/test/java/com/meoguri/linkocean/test/support/persistence/BasePersistenceTest.java
Labels: 북마크, 태그, 리팩토링

#204 [LO-201] 테스트 리팩토링
  build.gradle
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetBookmarksResponse.java
  src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetDetailedBookmarkResponse.java
  src/test/java/com/meoguri/linkocean/controller/user/LoginControllerTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/vo/TagIdsTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/entity/LinkMetadataTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/entity/vo/LinkTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByLinkQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/LinkMetadataRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/command/entity/ProfileTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/command/persistence/CustomProfileRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/command/persistence/FindProfileByIdQueryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/command/persistence/ProfileRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/command/service/FavoriteServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/command/service/FollowServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/command/service/ProfileServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/query/persistence/ProfileDaoImplTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/query/service/ProfileQueryServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/tag/entity/TagTest.java
  src/test/java/com/meoguri/linkocean/domain/tag/persistence/TagRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/user/entity/UserTest.java
  src/test/java/com/meoguri/linkocean/domain/user/entity/vo/EmailTest.java
  src/test/java/com/meoguri/linkocean/domain/user/persistence/UserRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/user/service/UserServiceImplTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/BookmarkRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/CategoryRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/FavoriteRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/FollowRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/LinkMetadataRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/LoginRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/NotificationRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/ProfileRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/ReactionRestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/RestDocs.java
  src/test/java/com/meoguri/linkocean/test/restdocs/support/RestDocsConfig.java
  src/test/java/com/meoguri/linkocean/test/restdocs/support/RestDocsTest.java
  src/test/java/com/meoguri/linkocean/test/restdocs/support/RestDocsTestSupport.java
  src/test/java/com/meoguri/linkocean/test/support/common/Fixture.java
  src/test/java/com/meoguri/linkocean/test/support/controller/BaseControllerTest.java
  src/test/java/com/meoguri/linkocean/test/support/controller/ControllerTest.java
  src/test/java/com/meoguri/linkocean/test/support/domain/entity/BaseEntityTest.java
  src/test/java/com/meoguri/linkocean/test/support/domain/entity/EntityTest.java
  src/test/java/com/meoguri/linkocean/test/support/domain/persistence/BasePersistenceTest.java
  src/test/java/com/meoguri/linkocean/test/support/domain/persistence/PersistenceTest.java
  src/test/java/com/meoguri/linkocean/test/support/domain/service/BaseServiceTest.java
  src/test/java/com/meoguri/linkocean/test/support/domain/service/ServiceTest.java
Labels: 세팅, 리팩토링

#205 [LO-202] jsoup 이슈 해결
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/vo/Link.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/entity/vo/LinkTest.java
Labels: 링크

#207 [LO-203] 북마크 링크메타데이터 ID 참조
  src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
  src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByIdQuery.java
  src/main/java/com/meoguri/linkocean/domain/linkmetadata/persistence/LinkMetadataRepository.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
  src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
  src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/LinkMetadataRepositoryTest.java
  src/test/java/com/meoguri/linkocean/domain/profile/command/entity/ProfileTest.java
  src/test/java/com/meoguri/linkocean/test/support/domain/entity/BaseEntityTest.java
  src/test/java/com/meoguri/linkocean/test/support/domain/persistence/BasePersistenceTest.java
Labels: 북마크, 리팩토링
